# Generated by Django 4.0.2 on 2022-08-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('target', models.CharField(max_length=200, null=True, verbose_name='対象')),
                ('content', models.TextField(verbose_name='本文')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('url_name', models.CharField(max_length=200, null=True, verbose_name='URL先の名前')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('category', models.CharField(choices=[('宿題について', '宿題について'), ('授業について', '授業について'), ('定期テストについて', '定期テストについて'), ('その他', 'その他')], max_length=50, verbose_name='カテゴリー')),
            ],
        ),
    ]
